/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as TeachersIdRouteImport } from './routes/teachers/$id'
import { Route as DashboardProfileCompleteRouteImport } from './routes/dashboard/profile-complete'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as CoursesIdRouteImport } from './routes/courses/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard/courses/index'
import { Route as DashboardBugsIndexRouteImport } from './routes/dashboard/bugs/index'
import { Route as DashboardStudentsIdRouteImport } from './routes/dashboard/students/$id'
import { Route as DashboardCoursesNewRouteImport } from './routes/dashboard/courses/new'
import { Route as DashboardBugsReportRouteImport } from './routes/dashboard/bugs/report'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminCoursesRouteImport } from './routes/dashboard/admin/courses'
import { Route as DashboardAdminCategoriesRouteImport } from './routes/dashboard/admin/categories'
import { Route as DashboardAdminBugsRouteImport } from './routes/dashboard/admin/bugs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardCoursesIdEditRouteImport } from './routes/dashboard/courses/$id/edit'
import { Route as DashboardCoursesIdContentRouteImport } from './routes/dashboard/courses/$id/content'
import { Route as DashboardAdminUsersIdRouteImport } from './routes/dashboard/admin/users/$id'
import { Route as DashboardAdminBugsIdRouteImport } from './routes/dashboard/admin/bugs/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileCompleteRoute =
  DashboardProfileCompleteRouteImport.update({
    id: '/profile-complete',
    path: '/profile-complete',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBugsIndexRoute = DashboardBugsIndexRouteImport.update({
  id: '/bugs/',
  path: '/bugs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsIdRoute = DashboardStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesNewRoute = DashboardCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBugsReportRoute = DashboardBugsReportRouteImport.update({
  id: '/bugs/report',
  path: '/bugs/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminCoursesRoute = DashboardAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminCategoriesRoute =
  DashboardAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminBugsRoute = DashboardAdminBugsRouteImport.update({
  id: '/admin/bugs',
  path: '/admin/bugs',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesIdEditRoute = DashboardCoursesIdEditRouteImport.update({
  id: '/courses/$id/edit',
  path: '/courses/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesIdContentRoute =
  DashboardCoursesIdContentRouteImport.update({
    id: '/courses/$id/content',
    path: '/courses/$id/content',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersIdRoute = DashboardAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardAdminUsersRoute,
} as any)
const DashboardAdminBugsIdRoute = DashboardAdminBugsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardAdminBugsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/profile-complete': typeof DashboardProfileCompleteRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/bugs': typeof DashboardAdminBugsRouteWithChildren
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRouteWithChildren
  '/dashboard/bugs/report': typeof DashboardBugsReportRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/dashboard/bugs/': typeof DashboardBugsIndexRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/admin/bugs/$id': typeof DashboardAdminBugsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/courses/$id/content': typeof DashboardCoursesIdContentRoute
  '/dashboard/courses/$id/edit': typeof DashboardCoursesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/profile-complete': typeof DashboardProfileCompleteRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/bugs': typeof DashboardAdminBugsRouteWithChildren
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRouteWithChildren
  '/dashboard/bugs/report': typeof DashboardBugsReportRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/dashboard/bugs': typeof DashboardBugsIndexRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/admin/bugs/$id': typeof DashboardAdminBugsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/courses/$id/content': typeof DashboardCoursesIdContentRoute
  '/dashboard/courses/$id/edit': typeof DashboardCoursesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/courses/$id': typeof CoursesIdRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/profile-complete': typeof DashboardProfileCompleteRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/bugs': typeof DashboardAdminBugsRouteWithChildren
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRouteWithChildren
  '/dashboard/bugs/report': typeof DashboardBugsReportRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/dashboard/bugs/': typeof DashboardBugsIndexRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/admin/bugs/$id': typeof DashboardAdminBugsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/courses/$id/content': typeof DashboardCoursesIdContentRoute
  '/dashboard/courses/$id/edit': typeof DashboardCoursesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/dashboard'
    | '/auth/sign-in'
    | '/courses/$id'
    | '/dashboard/profile'
    | '/dashboard/profile-complete'
    | '/teachers/$id'
    | '/courses/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/bugs'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/users'
    | '/dashboard/bugs/report'
    | '/dashboard/courses/new'
    | '/dashboard/students/$id'
    | '/dashboard/bugs/'
    | '/dashboard/courses/'
    | '/dashboard/admin/bugs/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/courses/$id/content'
    | '/dashboard/courses/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/auth/sign-in'
    | '/courses/$id'
    | '/dashboard/profile'
    | '/dashboard/profile-complete'
    | '/teachers/$id'
    | '/courses'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/admin/bugs'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/users'
    | '/dashboard/bugs/report'
    | '/dashboard/courses/new'
    | '/dashboard/students/$id'
    | '/dashboard/bugs'
    | '/dashboard/courses'
    | '/dashboard/admin/bugs/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/courses/$id/content'
    | '/dashboard/courses/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categories'
    | '/dashboard'
    | '/auth/sign-in'
    | '/courses/$id'
    | '/dashboard/profile'
    | '/dashboard/profile-complete'
    | '/teachers/$id'
    | '/courses/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/bugs'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/users'
    | '/dashboard/bugs/report'
    | '/dashboard/courses/new'
    | '/dashboard/students/$id'
    | '/dashboard/bugs/'
    | '/dashboard/courses/'
    | '/dashboard/admin/bugs/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/courses/$id/content'
    | '/dashboard/courses/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  CoursesIdRoute: typeof CoursesIdRoute
  TeachersIdRoute: typeof TeachersIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile-complete': {
      id: '/dashboard/profile-complete'
      path: '/profile-complete'
      fullPath: '/dashboard/profile-complete'
      preLoaderRoute: typeof DashboardProfileCompleteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bugs/': {
      id: '/dashboard/bugs/'
      path: '/bugs'
      fullPath: '/dashboard/bugs/'
      preLoaderRoute: typeof DashboardBugsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/$id': {
      id: '/dashboard/students/$id'
      path: '/students/$id'
      fullPath: '/dashboard/students/$id'
      preLoaderRoute: typeof DashboardStudentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/new': {
      id: '/dashboard/courses/new'
      path: '/courses/new'
      fullPath: '/dashboard/courses/new'
      preLoaderRoute: typeof DashboardCoursesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bugs/report': {
      id: '/dashboard/bugs/report'
      path: '/bugs/report'
      fullPath: '/dashboard/bugs/report'
      preLoaderRoute: typeof DashboardBugsReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/courses': {
      id: '/dashboard/admin/courses'
      path: '/admin/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof DashboardAdminCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/categories': {
      id: '/dashboard/admin/categories'
      path: '/admin/categories'
      fullPath: '/dashboard/admin/categories'
      preLoaderRoute: typeof DashboardAdminCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/bugs': {
      id: '/dashboard/admin/bugs'
      path: '/admin/bugs'
      fullPath: '/dashboard/admin/bugs'
      preLoaderRoute: typeof DashboardAdminBugsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses/$id/edit': {
      id: '/dashboard/courses/$id/edit'
      path: '/courses/$id/edit'
      fullPath: '/dashboard/courses/$id/edit'
      preLoaderRoute: typeof DashboardCoursesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/content': {
      id: '/dashboard/courses/$id/content'
      path: '/courses/$id/content'
      fullPath: '/dashboard/courses/$id/content'
      preLoaderRoute: typeof DashboardCoursesIdContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users/$id': {
      id: '/dashboard/admin/users/$id'
      path: '/$id'
      fullPath: '/dashboard/admin/users/$id'
      preLoaderRoute: typeof DashboardAdminUsersIdRouteImport
      parentRoute: typeof DashboardAdminUsersRoute
    }
    '/dashboard/admin/bugs/$id': {
      id: '/dashboard/admin/bugs/$id'
      path: '/$id'
      fullPath: '/dashboard/admin/bugs/$id'
      preLoaderRoute: typeof DashboardAdminBugsIdRouteImport
      parentRoute: typeof DashboardAdminBugsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAdminBugsRouteChildren {
  DashboardAdminBugsIdRoute: typeof DashboardAdminBugsIdRoute
}

const DashboardAdminBugsRouteChildren: DashboardAdminBugsRouteChildren = {
  DashboardAdminBugsIdRoute: DashboardAdminBugsIdRoute,
}

const DashboardAdminBugsRouteWithChildren =
  DashboardAdminBugsRoute._addFileChildren(DashboardAdminBugsRouteChildren)

interface DashboardAdminUsersRouteChildren {
  DashboardAdminUsersIdRoute: typeof DashboardAdminUsersIdRoute
}

const DashboardAdminUsersRouteChildren: DashboardAdminUsersRouteChildren = {
  DashboardAdminUsersIdRoute: DashboardAdminUsersIdRoute,
}

const DashboardAdminUsersRouteWithChildren =
  DashboardAdminUsersRoute._addFileChildren(DashboardAdminUsersRouteChildren)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProfileCompleteRoute: typeof DashboardProfileCompleteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminBugsRoute: typeof DashboardAdminBugsRouteWithChildren
  DashboardAdminCategoriesRoute: typeof DashboardAdminCategoriesRoute
  DashboardAdminCoursesRoute: typeof DashboardAdminCoursesRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRouteWithChildren
  DashboardBugsReportRoute: typeof DashboardBugsReportRoute
  DashboardCoursesNewRoute: typeof DashboardCoursesNewRoute
  DashboardStudentsIdRoute: typeof DashboardStudentsIdRoute
  DashboardBugsIndexRoute: typeof DashboardBugsIndexRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
  DashboardCoursesIdContentRoute: typeof DashboardCoursesIdContentRoute
  DashboardCoursesIdEditRoute: typeof DashboardCoursesIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProfileCompleteRoute: DashboardProfileCompleteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminBugsRoute: DashboardAdminBugsRouteWithChildren,
  DashboardAdminCategoriesRoute: DashboardAdminCategoriesRoute,
  DashboardAdminCoursesRoute: DashboardAdminCoursesRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRouteWithChildren,
  DashboardBugsReportRoute: DashboardBugsReportRoute,
  DashboardCoursesNewRoute: DashboardCoursesNewRoute,
  DashboardStudentsIdRoute: DashboardStudentsIdRoute,
  DashboardBugsIndexRoute: DashboardBugsIndexRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
  DashboardCoursesIdContentRoute: DashboardCoursesIdContentRoute,
  DashboardCoursesIdEditRoute: DashboardCoursesIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  CoursesIdRoute: CoursesIdRoute,
  TeachersIdRoute: TeachersIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
