/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiMobileAuthHandoffRouteImport } from './routes/api/mobile-auth-handoff'
import { Route as ApiPaymentReturnRouteImport } from './routes/api/payment-return'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardMyCoursesRouteImport } from './routes/dashboard/my-courses'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardProfileCompleteRouteImport } from './routes/dashboard/profile-complete'
import { Route as DevSeoPreviewRouteImport } from './routes/dev/seo-preview'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as TeachersSlugRouteImport } from './routes/teachers/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAccountantAnalyticsRouteImport } from './routes/dashboard/accountant/analytics'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard/admin/analytics'
import { Route as DashboardAdminCategoriesRouteImport } from './routes/dashboard/admin/categories'
import { Route as DashboardAdminCoursesRouteImport } from './routes/dashboard/admin/courses'
import { Route as DashboardAdminFeaturedCoursesRouteImport } from './routes/dashboard/admin/featured-courses'
import { Route as DashboardAdminMessageReportsRouteImport } from './routes/dashboard/admin/message-reports'
import { Route as DashboardAdminSmsRouteImport } from './routes/dashboard/admin/sms'
import { Route as DashboardBugsIndexRouteImport } from './routes/dashboard/bugs/index'
import { Route as DashboardBugsReportRouteImport } from './routes/dashboard/bugs/report'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard/courses/index'
import { Route as DashboardCoursesNewRouteImport } from './routes/dashboard/courses/new'
import { Route as DashboardLearnCourseIdRouteImport } from './routes/dashboard/learn/$courseId'
import { Route as DashboardNotificationsSendRouteImport } from './routes/dashboard/notifications/send'
import { Route as DashboardPaymentsIndexRouteImport } from './routes/dashboard/payments/index'
import { Route as DashboardPaymentsMockRouteImport } from './routes/dashboard/payments/mock'
import { Route as DashboardPaymentsReturnRouteImport } from './routes/dashboard/payments/return'
import { Route as DashboardStudentsIndexRouteImport } from './routes/dashboard/students/index'
import { Route as DashboardStudentsIdRouteImport } from './routes/dashboard/students/$id'
import { Route as DashboardAdminBugsIndexRouteImport } from './routes/dashboard/admin/bugs/index'
import { Route as DashboardAdminBugsIdRouteImport } from './routes/dashboard/admin/bugs/$id'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/dashboard/admin/users/index'
import { Route as DashboardAdminUsersIdRouteImport } from './routes/dashboard/admin/users/$id'
import { Route as DashboardCoursesIdAnalyticsRouteImport } from './routes/dashboard/courses/$id/analytics'
import { Route as DashboardCoursesIdContentRouteImport } from './routes/dashboard/courses/$id/content'
import { Route as DashboardCoursesIdDiscussionsRouteImport } from './routes/dashboard/courses/$id/discussions'
import { Route as DashboardCoursesIdEditRouteImport } from './routes/dashboard/courses/$id/edit'
import { Route as DashboardCoursesIdExamRouteImport } from './routes/dashboard/courses/$id/exam'
import { Route as DashboardCoursesIdNoticesRouteImport } from './routes/dashboard/courses/$id/notices'
import { Route as DashboardCoursesIdPublishRouteImport } from './routes/dashboard/courses/$id/publish'
import { Route as DashboardCoursesIdTestsRouteImport } from './routes/dashboard/courses/$id/tests'
import { Route as DashboardTestsTestIdIndexRouteImport } from './routes/dashboard/tests/$testId/index'
import { Route as DashboardTestsTestIdHistoryRouteImport } from './routes/dashboard/tests/$testId/history'
import { Route as DashboardTestsTestIdSubmissionsRouteImport } from './routes/dashboard/tests/$testId/submissions'
import { Route as DashboardTestsTestIdResultsSubmissionIdRouteImport } from './routes/dashboard/tests/$testId/results/$submissionId'
import { Route as DashboardTestsTestIdSubmissionsSubmissionIdRouteImport } from './routes/dashboard/tests/$testId/submissions/$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthHandoffRoute = ApiMobileAuthHandoffRouteImport.update({
  id: '/api/mobile-auth-handoff',
  path: '/api/mobile-auth-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentReturnRoute = ApiPaymentReturnRouteImport.update({
  id: '/api/payment-return',
  path: '/api/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyCoursesRoute = DashboardMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileCompleteRoute =
  DashboardProfileCompleteRouteImport.update({
    id: '/profile-complete',
    path: '/profile-complete',
    getParentRoute: () => DashboardRoute,
  } as any)
const DevSeoPreviewRoute = DevSeoPreviewRouteImport.update({
  id: '/dev/seo-preview',
  path: '/dev/seo-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersSlugRoute = TeachersSlugRouteImport.update({
  id: '/teachers/$slug',
  path: '/teachers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountantAnalyticsRoute =
  DashboardAccountantAnalyticsRouteImport.update({
    id: '/accountant/analytics',
    path: '/accountant/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminCategoriesRoute =
  DashboardAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminCoursesRoute = DashboardAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminFeaturedCoursesRoute =
  DashboardAdminFeaturedCoursesRouteImport.update({
    id: '/admin/featured-courses',
    path: '/admin/featured-courses',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminMessageReportsRoute =
  DashboardAdminMessageReportsRouteImport.update({
    id: '/admin/message-reports',
    path: '/admin/message-reports',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSmsRoute = DashboardAdminSmsRouteImport.update({
  id: '/admin/sms',
  path: '/admin/sms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBugsIndexRoute = DashboardBugsIndexRouteImport.update({
  id: '/bugs/',
  path: '/bugs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBugsReportRoute = DashboardBugsReportRouteImport.update({
  id: '/bugs/report',
  path: '/bugs/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesNewRoute = DashboardCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearnCourseIdRoute = DashboardLearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsSendRoute =
  DashboardNotificationsSendRouteImport.update({
    id: '/notifications/send',
    path: '/notifications/send',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPaymentsIndexRoute = DashboardPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsMockRoute = DashboardPaymentsMockRouteImport.update({
  id: '/payments/mock',
  path: '/payments/mock',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsReturnRoute = DashboardPaymentsReturnRouteImport.update({
  id: '/payments/return',
  path: '/payments/return',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsIndexRoute = DashboardStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsIdRoute = DashboardStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminBugsIndexRoute = DashboardAdminBugsIndexRouteImport.update({
  id: '/admin/bugs/',
  path: '/admin/bugs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminBugsIdRoute = DashboardAdminBugsIdRouteImport.update({
  id: '/admin/bugs/$id',
  path: '/admin/bugs/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersIdRoute = DashboardAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesIdAnalyticsRoute =
  DashboardCoursesIdAnalyticsRouteImport.update({
    id: '/courses/$id/analytics',
    path: '/courses/$id/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesIdContentRoute =
  DashboardCoursesIdContentRouteImport.update({
    id: '/courses/$id/content',
    path: '/courses/$id/content',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesIdDiscussionsRoute =
  DashboardCoursesIdDiscussionsRouteImport.update({
    id: '/courses/$id/discussions',
    path: '/courses/$id/discussions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesIdEditRoute = DashboardCoursesIdEditRouteImport.update({
  id: '/courses/$id/edit',
  path: '/courses/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesIdExamRoute = DashboardCoursesIdExamRouteImport.update({
  id: '/courses/$id/exam',
  path: '/courses/$id/exam',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesIdNoticesRoute =
  DashboardCoursesIdNoticesRouteImport.update({
    id: '/courses/$id/notices',
    path: '/courses/$id/notices',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesIdPublishRoute =
  DashboardCoursesIdPublishRouteImport.update({
    id: '/courses/$id/publish',
    path: '/courses/$id/publish',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesIdTestsRoute = DashboardCoursesIdTestsRouteImport.update({
  id: '/courses/$id/tests',
  path: '/courses/$id/tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestsTestIdIndexRoute =
  DashboardTestsTestIdIndexRouteImport.update({
    id: '/tests/$testId/',
    path: '/tests/$testId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTestsTestIdHistoryRoute =
  DashboardTestsTestIdHistoryRouteImport.update({
    id: '/tests/$testId/history',
    path: '/tests/$testId/history',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTestsTestIdSubmissionsRoute =
  DashboardTestsTestIdSubmissionsRouteImport.update({
    id: '/tests/$testId/submissions',
    path: '/tests/$testId/submissions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTestsTestIdResultsSubmissionIdRoute =
  DashboardTestsTestIdResultsSubmissionIdRouteImport.update({
    id: '/tests/$testId/results/$submissionId',
    path: '/tests/$testId/results/$submissionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTestsTestIdSubmissionsSubmissionIdRoute =
  DashboardTestsTestIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => DashboardTestsTestIdSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/mobile-auth-handoff': typeof ApiMobileAuthHandoffRoute
  '/api/payment-return': typeof ApiPaymentReturnRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-courses': typeof DashboardMyCoursesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/profile-complete': typeof DashboardProfileCompleteRoute
  '/dev/seo-preview': typeof DevSeoPreviewRoute
  '/teachers/$slug': typeof TeachersSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/accountant/analytics': typeof DashboardAccountantAnalyticsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/featured-courses': typeof DashboardAdminFeaturedCoursesRoute
  '/dashboard/admin/message-reports': typeof DashboardAdminMessageReportsRoute
  '/dashboard/admin/sms': typeof DashboardAdminSmsRoute
  '/dashboard/bugs/report': typeof DashboardBugsReportRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/learn/$courseId': typeof DashboardLearnCourseIdRoute
  '/dashboard/notifications/send': typeof DashboardNotificationsSendRoute
  '/dashboard/payments/mock': typeof DashboardPaymentsMockRoute
  '/dashboard/payments/return': typeof DashboardPaymentsReturnRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/dashboard/bugs/': typeof DashboardBugsIndexRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/admin/bugs/$id': typeof DashboardAdminBugsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/courses/$id/analytics': typeof DashboardCoursesIdAnalyticsRoute
  '/dashboard/courses/$id/content': typeof DashboardCoursesIdContentRoute
  '/dashboard/courses/$id/discussions': typeof DashboardCoursesIdDiscussionsRoute
  '/dashboard/courses/$id/edit': typeof DashboardCoursesIdEditRoute
  '/dashboard/courses/$id/exam': typeof DashboardCoursesIdExamRoute
  '/dashboard/courses/$id/notices': typeof DashboardCoursesIdNoticesRoute
  '/dashboard/courses/$id/publish': typeof DashboardCoursesIdPublishRoute
  '/dashboard/courses/$id/tests': typeof DashboardCoursesIdTestsRoute
  '/dashboard/tests/$testId/history': typeof DashboardTestsTestIdHistoryRoute
  '/dashboard/tests/$testId/submissions': typeof DashboardTestsTestIdSubmissionsRouteWithChildren
  '/dashboard/admin/bugs/': typeof DashboardAdminBugsIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/dashboard/tests/$testId/': typeof DashboardTestsTestIdIndexRoute
  '/dashboard/tests/$testId/results/$submissionId': typeof DashboardTestsTestIdResultsSubmissionIdRoute
  '/dashboard/tests/$testId/submissions/$submissionId': typeof DashboardTestsTestIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/mobile-auth-handoff': typeof ApiMobileAuthHandoffRoute
  '/api/payment-return': typeof ApiPaymentReturnRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-courses': typeof DashboardMyCoursesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/profile-complete': typeof DashboardProfileCompleteRoute
  '/dev/seo-preview': typeof DevSeoPreviewRoute
  '/teachers/$slug': typeof TeachersSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/accountant/analytics': typeof DashboardAccountantAnalyticsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/featured-courses': typeof DashboardAdminFeaturedCoursesRoute
  '/dashboard/admin/message-reports': typeof DashboardAdminMessageReportsRoute
  '/dashboard/admin/sms': typeof DashboardAdminSmsRoute
  '/dashboard/bugs/report': typeof DashboardBugsReportRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/learn/$courseId': typeof DashboardLearnCourseIdRoute
  '/dashboard/notifications/send': typeof DashboardNotificationsSendRoute
  '/dashboard/payments/mock': typeof DashboardPaymentsMockRoute
  '/dashboard/payments/return': typeof DashboardPaymentsReturnRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/dashboard/bugs': typeof DashboardBugsIndexRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/students': typeof DashboardStudentsIndexRoute
  '/dashboard/admin/bugs/$id': typeof DashboardAdminBugsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/courses/$id/analytics': typeof DashboardCoursesIdAnalyticsRoute
  '/dashboard/courses/$id/content': typeof DashboardCoursesIdContentRoute
  '/dashboard/courses/$id/discussions': typeof DashboardCoursesIdDiscussionsRoute
  '/dashboard/courses/$id/edit': typeof DashboardCoursesIdEditRoute
  '/dashboard/courses/$id/exam': typeof DashboardCoursesIdExamRoute
  '/dashboard/courses/$id/notices': typeof DashboardCoursesIdNoticesRoute
  '/dashboard/courses/$id/publish': typeof DashboardCoursesIdPublishRoute
  '/dashboard/courses/$id/tests': typeof DashboardCoursesIdTestsRoute
  '/dashboard/tests/$testId/history': typeof DashboardTestsTestIdHistoryRoute
  '/dashboard/tests/$testId/submissions': typeof DashboardTestsTestIdSubmissionsRouteWithChildren
  '/dashboard/admin/bugs': typeof DashboardAdminBugsIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
  '/dashboard/tests/$testId': typeof DashboardTestsTestIdIndexRoute
  '/dashboard/tests/$testId/results/$submissionId': typeof DashboardTestsTestIdResultsSubmissionIdRoute
  '/dashboard/tests/$testId/submissions/$submissionId': typeof DashboardTestsTestIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/mobile-auth-handoff': typeof ApiMobileAuthHandoffRoute
  '/api/payment-return': typeof ApiPaymentReturnRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-courses': typeof DashboardMyCoursesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/profile-complete': typeof DashboardProfileCompleteRoute
  '/dev/seo-preview': typeof DevSeoPreviewRoute
  '/teachers/$slug': typeof TeachersSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/accountant/analytics': typeof DashboardAccountantAnalyticsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/featured-courses': typeof DashboardAdminFeaturedCoursesRoute
  '/dashboard/admin/message-reports': typeof DashboardAdminMessageReportsRoute
  '/dashboard/admin/sms': typeof DashboardAdminSmsRoute
  '/dashboard/bugs/report': typeof DashboardBugsReportRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/learn/$courseId': typeof DashboardLearnCourseIdRoute
  '/dashboard/notifications/send': typeof DashboardNotificationsSendRoute
  '/dashboard/payments/mock': typeof DashboardPaymentsMockRoute
  '/dashboard/payments/return': typeof DashboardPaymentsReturnRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdRoute
  '/dashboard/bugs/': typeof DashboardBugsIndexRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/admin/bugs/$id': typeof DashboardAdminBugsIdRoute
  '/dashboard/admin/users/$id': typeof DashboardAdminUsersIdRoute
  '/dashboard/courses/$id/analytics': typeof DashboardCoursesIdAnalyticsRoute
  '/dashboard/courses/$id/content': typeof DashboardCoursesIdContentRoute
  '/dashboard/courses/$id/discussions': typeof DashboardCoursesIdDiscussionsRoute
  '/dashboard/courses/$id/edit': typeof DashboardCoursesIdEditRoute
  '/dashboard/courses/$id/exam': typeof DashboardCoursesIdExamRoute
  '/dashboard/courses/$id/notices': typeof DashboardCoursesIdNoticesRoute
  '/dashboard/courses/$id/publish': typeof DashboardCoursesIdPublishRoute
  '/dashboard/courses/$id/tests': typeof DashboardCoursesIdTestsRoute
  '/dashboard/tests/$testId/history': typeof DashboardTestsTestIdHistoryRoute
  '/dashboard/tests/$testId/submissions': typeof DashboardTestsTestIdSubmissionsRouteWithChildren
  '/dashboard/admin/bugs/': typeof DashboardAdminBugsIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/dashboard/tests/$testId/': typeof DashboardTestsTestIdIndexRoute
  '/dashboard/tests/$testId/results/$submissionId': typeof DashboardTestsTestIdResultsSubmissionIdRoute
  '/dashboard/tests/$testId/submissions/$submissionId': typeof DashboardTestsTestIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api/mobile-auth-handoff'
    | '/api/payment-return'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$slug'
    | '/courses/$slug'
    | '/dashboard/analytics'
    | '/dashboard/messages'
    | '/dashboard/my-courses'
    | '/dashboard/profile'
    | '/dashboard/profile-complete'
    | '/dev/seo-preview'
    | '/teachers/$slug'
    | '/courses/'
    | '/dashboard/'
    | '/teachers/'
    | '/api/auth/$'
    | '/dashboard/accountant/analytics'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/featured-courses'
    | '/dashboard/admin/message-reports'
    | '/dashboard/admin/sms'
    | '/dashboard/bugs/report'
    | '/dashboard/courses/new'
    | '/dashboard/learn/$courseId'
    | '/dashboard/notifications/send'
    | '/dashboard/payments/mock'
    | '/dashboard/payments/return'
    | '/dashboard/students/$id'
    | '/dashboard/bugs/'
    | '/dashboard/courses/'
    | '/dashboard/payments/'
    | '/dashboard/students/'
    | '/dashboard/admin/bugs/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/courses/$id/analytics'
    | '/dashboard/courses/$id/content'
    | '/dashboard/courses/$id/discussions'
    | '/dashboard/courses/$id/edit'
    | '/dashboard/courses/$id/exam'
    | '/dashboard/courses/$id/notices'
    | '/dashboard/courses/$id/publish'
    | '/dashboard/courses/$id/tests'
    | '/dashboard/tests/$testId/history'
    | '/dashboard/tests/$testId/submissions'
    | '/dashboard/admin/bugs/'
    | '/dashboard/admin/users/'
    | '/dashboard/tests/$testId/'
    | '/dashboard/tests/$testId/results/$submissionId'
    | '/dashboard/tests/$testId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api/mobile-auth-handoff'
    | '/api/payment-return'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$slug'
    | '/courses/$slug'
    | '/dashboard/analytics'
    | '/dashboard/messages'
    | '/dashboard/my-courses'
    | '/dashboard/profile'
    | '/dashboard/profile-complete'
    | '/dev/seo-preview'
    | '/teachers/$slug'
    | '/courses'
    | '/dashboard'
    | '/teachers'
    | '/api/auth/$'
    | '/dashboard/accountant/analytics'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/featured-courses'
    | '/dashboard/admin/message-reports'
    | '/dashboard/admin/sms'
    | '/dashboard/bugs/report'
    | '/dashboard/courses/new'
    | '/dashboard/learn/$courseId'
    | '/dashboard/notifications/send'
    | '/dashboard/payments/mock'
    | '/dashboard/payments/return'
    | '/dashboard/students/$id'
    | '/dashboard/bugs'
    | '/dashboard/courses'
    | '/dashboard/payments'
    | '/dashboard/students'
    | '/dashboard/admin/bugs/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/courses/$id/analytics'
    | '/dashboard/courses/$id/content'
    | '/dashboard/courses/$id/discussions'
    | '/dashboard/courses/$id/edit'
    | '/dashboard/courses/$id/exam'
    | '/dashboard/courses/$id/notices'
    | '/dashboard/courses/$id/publish'
    | '/dashboard/courses/$id/tests'
    | '/dashboard/tests/$testId/history'
    | '/dashboard/tests/$testId/submissions'
    | '/dashboard/admin/bugs'
    | '/dashboard/admin/users'
    | '/dashboard/tests/$testId'
    | '/dashboard/tests/$testId/results/$submissionId'
    | '/dashboard/tests/$testId/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/api/mobile-auth-handoff'
    | '/api/payment-return'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$slug'
    | '/courses/$slug'
    | '/dashboard/analytics'
    | '/dashboard/messages'
    | '/dashboard/my-courses'
    | '/dashboard/profile'
    | '/dashboard/profile-complete'
    | '/dev/seo-preview'
    | '/teachers/$slug'
    | '/courses/'
    | '/dashboard/'
    | '/teachers/'
    | '/api/auth/$'
    | '/dashboard/accountant/analytics'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/featured-courses'
    | '/dashboard/admin/message-reports'
    | '/dashboard/admin/sms'
    | '/dashboard/bugs/report'
    | '/dashboard/courses/new'
    | '/dashboard/learn/$courseId'
    | '/dashboard/notifications/send'
    | '/dashboard/payments/mock'
    | '/dashboard/payments/return'
    | '/dashboard/students/$id'
    | '/dashboard/bugs/'
    | '/dashboard/courses/'
    | '/dashboard/payments/'
    | '/dashboard/students/'
    | '/dashboard/admin/bugs/$id'
    | '/dashboard/admin/users/$id'
    | '/dashboard/courses/$id/analytics'
    | '/dashboard/courses/$id/content'
    | '/dashboard/courses/$id/discussions'
    | '/dashboard/courses/$id/edit'
    | '/dashboard/courses/$id/exam'
    | '/dashboard/courses/$id/notices'
    | '/dashboard/courses/$id/publish'
    | '/dashboard/courses/$id/tests'
    | '/dashboard/tests/$testId/history'
    | '/dashboard/tests/$testId/submissions'
    | '/dashboard/admin/bugs/'
    | '/dashboard/admin/users/'
    | '/dashboard/tests/$testId/'
    | '/dashboard/tests/$testId/results/$submissionId'
    | '/dashboard/tests/$testId/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiMobileAuthHandoffRoute: typeof ApiMobileAuthHandoffRoute
  ApiPaymentReturnRoute: typeof ApiPaymentReturnRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  DevSeoPreviewRoute: typeof DevSeoPreviewRoute
  TeachersSlugRoute: typeof TeachersSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-auth-handoff': {
      id: '/api/mobile-auth-handoff'
      path: '/api/mobile-auth-handoff'
      fullPath: '/api/mobile-auth-handoff'
      preLoaderRoute: typeof ApiMobileAuthHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-return': {
      id: '/api/payment-return'
      path: '/api/payment-return'
      fullPath: '/api/payment-return'
      preLoaderRoute: typeof ApiPaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-courses': {
      id: '/dashboard/my-courses'
      path: '/my-courses'
      fullPath: '/dashboard/my-courses'
      preLoaderRoute: typeof DashboardMyCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile-complete': {
      id: '/dashboard/profile-complete'
      path: '/profile-complete'
      fullPath: '/dashboard/profile-complete'
      preLoaderRoute: typeof DashboardProfileCompleteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dev/seo-preview': {
      id: '/dev/seo-preview'
      path: '/dev/seo-preview'
      fullPath: '/dev/seo-preview'
      preLoaderRoute: typeof DevSeoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$slug': {
      id: '/teachers/$slug'
      path: '/teachers/$slug'
      fullPath: '/teachers/$slug'
      preLoaderRoute: typeof TeachersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/accountant/analytics': {
      id: '/dashboard/accountant/analytics'
      path: '/accountant/analytics'
      fullPath: '/dashboard/accountant/analytics'
      preLoaderRoute: typeof DashboardAccountantAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/categories': {
      id: '/dashboard/admin/categories'
      path: '/admin/categories'
      fullPath: '/dashboard/admin/categories'
      preLoaderRoute: typeof DashboardAdminCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/courses': {
      id: '/dashboard/admin/courses'
      path: '/admin/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof DashboardAdminCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/featured-courses': {
      id: '/dashboard/admin/featured-courses'
      path: '/admin/featured-courses'
      fullPath: '/dashboard/admin/featured-courses'
      preLoaderRoute: typeof DashboardAdminFeaturedCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/message-reports': {
      id: '/dashboard/admin/message-reports'
      path: '/admin/message-reports'
      fullPath: '/dashboard/admin/message-reports'
      preLoaderRoute: typeof DashboardAdminMessageReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/sms': {
      id: '/dashboard/admin/sms'
      path: '/admin/sms'
      fullPath: '/dashboard/admin/sms'
      preLoaderRoute: typeof DashboardAdminSmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bugs/': {
      id: '/dashboard/bugs/'
      path: '/bugs'
      fullPath: '/dashboard/bugs/'
      preLoaderRoute: typeof DashboardBugsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bugs/report': {
      id: '/dashboard/bugs/report'
      path: '/bugs/report'
      fullPath: '/dashboard/bugs/report'
      preLoaderRoute: typeof DashboardBugsReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/new': {
      id: '/dashboard/courses/new'
      path: '/courses/new'
      fullPath: '/dashboard/courses/new'
      preLoaderRoute: typeof DashboardCoursesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learn/$courseId': {
      id: '/dashboard/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/dashboard/learn/$courseId'
      preLoaderRoute: typeof DashboardLearnCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications/send': {
      id: '/dashboard/notifications/send'
      path: '/notifications/send'
      fullPath: '/dashboard/notifications/send'
      preLoaderRoute: typeof DashboardNotificationsSendRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments/': {
      id: '/dashboard/payments/'
      path: '/payments'
      fullPath: '/dashboard/payments/'
      preLoaderRoute: typeof DashboardPaymentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments/mock': {
      id: '/dashboard/payments/mock'
      path: '/payments/mock'
      fullPath: '/dashboard/payments/mock'
      preLoaderRoute: typeof DashboardPaymentsMockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments/return': {
      id: '/dashboard/payments/return'
      path: '/payments/return'
      fullPath: '/dashboard/payments/return'
      preLoaderRoute: typeof DashboardPaymentsReturnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/': {
      id: '/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof DashboardStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/$id': {
      id: '/dashboard/students/$id'
      path: '/students/$id'
      fullPath: '/dashboard/students/$id'
      preLoaderRoute: typeof DashboardStudentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/bugs/': {
      id: '/dashboard/admin/bugs/'
      path: '/admin/bugs'
      fullPath: '/dashboard/admin/bugs/'
      preLoaderRoute: typeof DashboardAdminBugsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/bugs/$id': {
      id: '/dashboard/admin/bugs/$id'
      path: '/admin/bugs/$id'
      fullPath: '/dashboard/admin/bugs/$id'
      preLoaderRoute: typeof DashboardAdminBugsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users/': {
      id: '/dashboard/admin/users/'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users/'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users/$id': {
      id: '/dashboard/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/dashboard/admin/users/$id'
      preLoaderRoute: typeof DashboardAdminUsersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/analytics': {
      id: '/dashboard/courses/$id/analytics'
      path: '/courses/$id/analytics'
      fullPath: '/dashboard/courses/$id/analytics'
      preLoaderRoute: typeof DashboardCoursesIdAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/content': {
      id: '/dashboard/courses/$id/content'
      path: '/courses/$id/content'
      fullPath: '/dashboard/courses/$id/content'
      preLoaderRoute: typeof DashboardCoursesIdContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/discussions': {
      id: '/dashboard/courses/$id/discussions'
      path: '/courses/$id/discussions'
      fullPath: '/dashboard/courses/$id/discussions'
      preLoaderRoute: typeof DashboardCoursesIdDiscussionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/edit': {
      id: '/dashboard/courses/$id/edit'
      path: '/courses/$id/edit'
      fullPath: '/dashboard/courses/$id/edit'
      preLoaderRoute: typeof DashboardCoursesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/exam': {
      id: '/dashboard/courses/$id/exam'
      path: '/courses/$id/exam'
      fullPath: '/dashboard/courses/$id/exam'
      preLoaderRoute: typeof DashboardCoursesIdExamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/notices': {
      id: '/dashboard/courses/$id/notices'
      path: '/courses/$id/notices'
      fullPath: '/dashboard/courses/$id/notices'
      preLoaderRoute: typeof DashboardCoursesIdNoticesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/publish': {
      id: '/dashboard/courses/$id/publish'
      path: '/courses/$id/publish'
      fullPath: '/dashboard/courses/$id/publish'
      preLoaderRoute: typeof DashboardCoursesIdPublishRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id/tests': {
      id: '/dashboard/courses/$id/tests'
      path: '/courses/$id/tests'
      fullPath: '/dashboard/courses/$id/tests'
      preLoaderRoute: typeof DashboardCoursesIdTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests/$testId/': {
      id: '/dashboard/tests/$testId/'
      path: '/tests/$testId'
      fullPath: '/dashboard/tests/$testId/'
      preLoaderRoute: typeof DashboardTestsTestIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests/$testId/history': {
      id: '/dashboard/tests/$testId/history'
      path: '/tests/$testId/history'
      fullPath: '/dashboard/tests/$testId/history'
      preLoaderRoute: typeof DashboardTestsTestIdHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests/$testId/submissions': {
      id: '/dashboard/tests/$testId/submissions'
      path: '/tests/$testId/submissions'
      fullPath: '/dashboard/tests/$testId/submissions'
      preLoaderRoute: typeof DashboardTestsTestIdSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests/$testId/results/$submissionId': {
      id: '/dashboard/tests/$testId/results/$submissionId'
      path: '/tests/$testId/results/$submissionId'
      fullPath: '/dashboard/tests/$testId/results/$submissionId'
      preLoaderRoute: typeof DashboardTestsTestIdResultsSubmissionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests/$testId/submissions/$submissionId': {
      id: '/dashboard/tests/$testId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/dashboard/tests/$testId/submissions/$submissionId'
      preLoaderRoute: typeof DashboardTestsTestIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof DashboardTestsTestIdSubmissionsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface DashboardTestsTestIdSubmissionsRouteChildren {
  DashboardTestsTestIdSubmissionsSubmissionIdRoute: typeof DashboardTestsTestIdSubmissionsSubmissionIdRoute
}

const DashboardTestsTestIdSubmissionsRouteChildren: DashboardTestsTestIdSubmissionsRouteChildren =
  {
    DashboardTestsTestIdSubmissionsSubmissionIdRoute:
      DashboardTestsTestIdSubmissionsSubmissionIdRoute,
  }

const DashboardTestsTestIdSubmissionsRouteWithChildren =
  DashboardTestsTestIdSubmissionsRoute._addFileChildren(
    DashboardTestsTestIdSubmissionsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyCoursesRoute: typeof DashboardMyCoursesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProfileCompleteRoute: typeof DashboardProfileCompleteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountantAnalyticsRoute: typeof DashboardAccountantAnalyticsRoute
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminCategoriesRoute: typeof DashboardAdminCategoriesRoute
  DashboardAdminCoursesRoute: typeof DashboardAdminCoursesRoute
  DashboardAdminFeaturedCoursesRoute: typeof DashboardAdminFeaturedCoursesRoute
  DashboardAdminMessageReportsRoute: typeof DashboardAdminMessageReportsRoute
  DashboardAdminSmsRoute: typeof DashboardAdminSmsRoute
  DashboardBugsReportRoute: typeof DashboardBugsReportRoute
  DashboardCoursesNewRoute: typeof DashboardCoursesNewRoute
  DashboardLearnCourseIdRoute: typeof DashboardLearnCourseIdRoute
  DashboardNotificationsSendRoute: typeof DashboardNotificationsSendRoute
  DashboardPaymentsMockRoute: typeof DashboardPaymentsMockRoute
  DashboardPaymentsReturnRoute: typeof DashboardPaymentsReturnRoute
  DashboardStudentsIdRoute: typeof DashboardStudentsIdRoute
  DashboardBugsIndexRoute: typeof DashboardBugsIndexRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
  DashboardPaymentsIndexRoute: typeof DashboardPaymentsIndexRoute
  DashboardStudentsIndexRoute: typeof DashboardStudentsIndexRoute
  DashboardAdminBugsIdRoute: typeof DashboardAdminBugsIdRoute
  DashboardAdminUsersIdRoute: typeof DashboardAdminUsersIdRoute
  DashboardCoursesIdAnalyticsRoute: typeof DashboardCoursesIdAnalyticsRoute
  DashboardCoursesIdContentRoute: typeof DashboardCoursesIdContentRoute
  DashboardCoursesIdDiscussionsRoute: typeof DashboardCoursesIdDiscussionsRoute
  DashboardCoursesIdEditRoute: typeof DashboardCoursesIdEditRoute
  DashboardCoursesIdExamRoute: typeof DashboardCoursesIdExamRoute
  DashboardCoursesIdNoticesRoute: typeof DashboardCoursesIdNoticesRoute
  DashboardCoursesIdPublishRoute: typeof DashboardCoursesIdPublishRoute
  DashboardCoursesIdTestsRoute: typeof DashboardCoursesIdTestsRoute
  DashboardTestsTestIdHistoryRoute: typeof DashboardTestsTestIdHistoryRoute
  DashboardTestsTestIdSubmissionsRoute: typeof DashboardTestsTestIdSubmissionsRouteWithChildren
  DashboardAdminBugsIndexRoute: typeof DashboardAdminBugsIndexRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
  DashboardTestsTestIdIndexRoute: typeof DashboardTestsTestIdIndexRoute
  DashboardTestsTestIdResultsSubmissionIdRoute: typeof DashboardTestsTestIdResultsSubmissionIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyCoursesRoute: DashboardMyCoursesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProfileCompleteRoute: DashboardProfileCompleteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountantAnalyticsRoute: DashboardAccountantAnalyticsRoute,
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminCategoriesRoute: DashboardAdminCategoriesRoute,
  DashboardAdminCoursesRoute: DashboardAdminCoursesRoute,
  DashboardAdminFeaturedCoursesRoute: DashboardAdminFeaturedCoursesRoute,
  DashboardAdminMessageReportsRoute: DashboardAdminMessageReportsRoute,
  DashboardAdminSmsRoute: DashboardAdminSmsRoute,
  DashboardBugsReportRoute: DashboardBugsReportRoute,
  DashboardCoursesNewRoute: DashboardCoursesNewRoute,
  DashboardLearnCourseIdRoute: DashboardLearnCourseIdRoute,
  DashboardNotificationsSendRoute: DashboardNotificationsSendRoute,
  DashboardPaymentsMockRoute: DashboardPaymentsMockRoute,
  DashboardPaymentsReturnRoute: DashboardPaymentsReturnRoute,
  DashboardStudentsIdRoute: DashboardStudentsIdRoute,
  DashboardBugsIndexRoute: DashboardBugsIndexRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
  DashboardPaymentsIndexRoute: DashboardPaymentsIndexRoute,
  DashboardStudentsIndexRoute: DashboardStudentsIndexRoute,
  DashboardAdminBugsIdRoute: DashboardAdminBugsIdRoute,
  DashboardAdminUsersIdRoute: DashboardAdminUsersIdRoute,
  DashboardCoursesIdAnalyticsRoute: DashboardCoursesIdAnalyticsRoute,
  DashboardCoursesIdContentRoute: DashboardCoursesIdContentRoute,
  DashboardCoursesIdDiscussionsRoute: DashboardCoursesIdDiscussionsRoute,
  DashboardCoursesIdEditRoute: DashboardCoursesIdEditRoute,
  DashboardCoursesIdExamRoute: DashboardCoursesIdExamRoute,
  DashboardCoursesIdNoticesRoute: DashboardCoursesIdNoticesRoute,
  DashboardCoursesIdPublishRoute: DashboardCoursesIdPublishRoute,
  DashboardCoursesIdTestsRoute: DashboardCoursesIdTestsRoute,
  DashboardTestsTestIdHistoryRoute: DashboardTestsTestIdHistoryRoute,
  DashboardTestsTestIdSubmissionsRoute:
    DashboardTestsTestIdSubmissionsRouteWithChildren,
  DashboardAdminBugsIndexRoute: DashboardAdminBugsIndexRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
  DashboardTestsTestIdIndexRoute: DashboardTestsTestIdIndexRoute,
  DashboardTestsTestIdResultsSubmissionIdRoute:
    DashboardTestsTestIdResultsSubmissionIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiMobileAuthHandoffRoute: ApiMobileAuthHandoffRoute,
  ApiPaymentReturnRoute: ApiPaymentReturnRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  DevSeoPreviewRoute: DevSeoPreviewRoute,
  TeachersSlugRoute: TeachersSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
