import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";

/**
 * Bakes KaTeX's stylesheet and the font faces it needs into one TypeScript
 * module for the Expo app.
 *
 * The app renders maths in a WebView, and a WebView loads nothing the bundle
 * does not carry: a `<link>` to a CDN would leave a student on a bad connection
 * — or in an exam hall with no signal — looking at fallback glyphs where the
 * integral signs should be. So the CSS is inlined and every `url(...)` is
 * replaced by a `data:` URI.
 *
 * Only woff2 is kept, and only the faces the stylesheet actually references.
 * The ttf and woff copies alongside them are for browsers that predate every
 * device this app runs on, and carrying all sixty files would treble the size.
 *
 * Run with `bun run build:katex-assets` after upgrading katex, and commit the
 * generated file — the app builds without a build step of its own.
 */

const require = createRequire(import.meta.url);
const katexCssPath = require.resolve("katex/dist/katex.min.css");
const fontsDirectory = path.join(path.dirname(katexCssPath), "fonts");
const outputPath = path.join(
  import.meta.dirname,
  "..",
  "..",
  "apps",
  "mobile",
  "src",
  "components",
  "math",
  "katex-css.ts"
);

async function fontDataUri(fileName: string): Promise<string> {
  const bytes = await readFile(path.join(fontsDirectory, fileName));

  return `data:font/woff2;base64,${bytes.toString("base64")}`;
}

async function main(): Promise<void> {
  const css = await readFile(katexCssPath, "utf8");
  const used = new Set<string>();
  // `url(fonts/KaTeX_Main-Regular.woff2) format("woff2")`
  const urlPattern = /url\((fonts\/([A-Za-z0-9_-]+\.woff2))\)/g;

  for (const match of css.matchAll(urlPattern)) {
    const fileName = match[2];

    if (fileName !== undefined) {
      used.add(fileName);
    }
  }

  const dataUris = new Map<string, string>();

  for (const fileName of used) {
    dataUris.set(fileName, await fontDataUri(fileName));
  }

  // Drop the ttf/woff fallbacks in the same `src` list: they would resolve to
  // nothing inside the WebView and each is a request that fails.
  const inlined = css
    .replace(/src:[^;]+;/g, (declaration) => {
      const woff2 = /url\(fonts\/([A-Za-z0-9_-]+\.woff2)\)/.exec(declaration);
      const fileName = woff2?.[1];
      const uri = fileName === undefined ? undefined : dataUris.get(fileName);

      return uri === undefined ? declaration : `src:url(${uri}) format("woff2");`;
    })
    .replace(/\s+/g, " ")
    .trim();

  const generated = `/* Generated by tooling/scripts/build-katex-assets.ts. Do not edit.
 *
 * KaTeX's stylesheet with its woff2 faces inlined, so the WebView that renders
 * maths needs no network. Regenerate after upgrading katex:
 *   bun run --filter @genex/scripts build:katex-assets
 */

export const katexCss = ${JSON.stringify(inlined)};
`;

  await writeFile(outputPath, generated, "utf8");

  const kilobytes = Math.round(generated.length / 1024);

  console.log(`Wrote ${outputPath} (${String(used.size)} faces, ${String(kilobytes)} KB)`);
}

await main();
