import { AdminController } from "@/controllers/admin-controller";
import { AdminDashboardController } from "@/controllers/admin-dashboard-controller";
import { AdminUserController } from "@/controllers/admin-user-controller";
import { AuthController } from "@/controllers/auth-controller";
import { BugReportController } from "@/controllers/bug-report-controller";
import { CategoryController } from "@/controllers/category-controller";
import { HealthController } from "@/controllers/health-controller";
import { NotImplementedController } from "@/controllers/not-implemented-controller";
import { ProfileController } from "@/controllers/profile-controller";
import { UploadController } from "@/controllers/upload-controller";
import { queues } from "@/lib/queues";
import { redis } from "@/lib/redis";
import { AdminDashboardRepository } from "@/repositories/admin-dashboard-repository";
import { AdminUserRepository } from "@/repositories/admin-user-repository";
import { AuthSessionRepository } from "@/repositories/auth-session-repository";
import { BugReportRepository } from "@/repositories/bug-report-repository";
import { CategoryRepository } from "@/repositories/category-repository";
import { HealthRepository } from "@/repositories/health-repository";
import { ProfileRepository } from "@/repositories/profile-repository";
import { StaffAccountRepository } from "@/repositories/staff-account-repository";
import { AdminDashboardService } from "@/services/admin-dashboard-service";
import { AdminUserService } from "@/services/admin-user-service";
import { AuthGuardService } from "@/services/auth-guard-service";
import { BugReportService } from "@/services/bug-report-service";
import { CategoryService } from "@/services/category-service";
import { HealthService } from "@/services/health-service";
import { NotImplementedService } from "@/services/not-implemented-service";
import { ProfileService } from "@/services/profile-service";
import { StaffAccountService } from "@/services/staff-account-service";
import { UploadService } from "@/services/upload-service";

const healthRepository = new HealthRepository(redis, queues);
const adminDashboardRepository = new AdminDashboardRepository();
const adminUserRepository = new AdminUserRepository();
const authSessionRepository = new AuthSessionRepository();
const bugReportRepository = new BugReportRepository();
const categoryRepository = new CategoryRepository();
const profileRepository = new ProfileRepository();
const staffAccountRepository = new StaffAccountRepository();
const adminDashboardService = new AdminDashboardService(adminDashboardRepository);
const healthService = new HealthService(healthRepository);
const authGuardService = new AuthGuardService(authSessionRepository);
const staffAccountService = new StaffAccountService(staffAccountRepository);
const adminUserService = new AdminUserService(adminUserRepository, authSessionRepository, staffAccountService);
const bugReportService = new BugReportService(bugReportRepository);
const categoryService = new CategoryService(categoryRepository);
const profileService = new ProfileService(profileRepository);
const notImplementedService = new NotImplementedService();
const uploadService = new UploadService();

export const adminController = new AdminController(staffAccountService);
export const adminDashboardController = new AdminDashboardController(adminDashboardService);
export const adminUserController = new AdminUserController(adminUserService);
export const authController = new AuthController();
export { authGuardService };
export const bugReportController = new BugReportController(bugReportService);
export const categoryController = new CategoryController(categoryService);
export const healthController = new HealthController(healthService);
export const notImplementedController = new NotImplementedController(notImplementedService);
export const profileController = new ProfileController(profileService);
export const uploadController = new UploadController(uploadService);
