/**
 * The Bijoy/SutonnyMJ glyph tables, ported byte-for-byte from the owner's other
 * project (`mehedi_bhai/src/shared/lib/bijoy/charMap.ts`).
 *
 * Bijoy is an ASCII encoding: a `K` in a SutonnyMJ document is a ক, and the
 * bytes only look like Bengali when that font is installed. Pasted anywhere
 * else -- including here -- they arrive as gibberish, which is why the app
 * converts them on paste rather than asking teachers to retype a paper.
 *
 * Several keys are single control or private-use characters that do not survive
 * being retyped. Copy this file rather than editing it by hand.
 */

export const PRE_CONVERSION_MAP: Record<string, string> = {
  " +": " ",
  yy: "y",
  vv: "v",
  "„„": "„",
  "": "",
  "y&": "y",
  "„&": "„",
  "‡u": "u‡",
  wu: "uw",
  " ,": ",",
  " \\|": "\\|",
  "\\\\ ": "",
  " \\\\": "",
  "\\\\": "",
  "\n +": "\n",
  " +\n": "\n",
  "\n\n\n\n\n": "\n\n",
  "\n\n\n\n": "\n\n",
  "\n\n\n": "\n\n",
  "v©": "©v",
};

export const CONVERSION_MAP: Record<string, string> = {
  "°": "ক্ক",
  "±": "ক্ট",
  "²": "ক্ষ্ণ",
  "³": "ক্ত",
  "´": "ক্ম",
  µ: "ক্র",
  "¶": "ক্ষ",
  "·": "ক্স",
  "¸": "গু",
  "¹": "জ্ঞ",
  º: "গ্দ",
  "»": "গ্ধ",
  "¼": "ঙ্ক",
  "½": "ঙ্গ",
  "¾": "জ্জ",
  "¿": "্ত্র",
  À: "জ্ঝ",
  Á: "জ্ঞ",
  Â: "ঞ্চ",
  Ã: "ঞ্ছ",
  Ä: "ঞ্জ",
  Å: "ঞ্ঝ",
  Æ: "ট্ট",
  Ç: "ড্ড",
  È: "ণ্ট",
  É: "ণ্ঠ",
  Ê: "ণ্ড",
  Ë: "ত্ত",
  Ì: "ত্থ",
  Î: "ত্র",
  Ï: "দ্দ",
  Ð: "ণ্ড",
  Ñ: "-",
  Ò: '"',
  Ó: '"',
  Ô: "'",
  Õ: "'",
  "×": "দ্ধ",
  Ø: "দ্ব",
  Ù: "দ্ম",
  Ú: "ন্ঠ",
  Û: "ন্ড",
  Ü: "ন্ধ",
  Ý: "ন্স",
  Þ: "প্ট",
  ß: "প্ত",
  à: "প্প",
  á: "প্স",
  â: "ব্জ",
  ã: "ব্দ",
  ä: "ব্ধ",
  å: "ভ্র",
  ç: "ম্ফ",
  é: "ল্ক",
  ê: "ল্গ",
  ë: "ল্ট",
  ì: "ল্ড",
  í: "ল্প",
  î: "ল্ফ",
  ï: "শু",
  ð: "শ্চ",
  ñ: "শ্ছ",
  ò: "ষ্ণ",
  ó: "ষ্ট",
  ô: "ষ্ঠ",
  õ: "ষ্ফ",
  ö: "স্খ",
  "÷": "স্ট",
  ø: "স্ন",
  ù: "স্ফ",
  û: "হু",
  ü: "হৃ",
  ý: "হ্ন",
  ÿ: "ক্ষ",
  þ: "হ্ম",
  A: "অ",
  B: "ই",
  C: "ঈ",
  D: "উ",
  E: "ঊ",
  F: "ঋ",
  G: "এ",
  H: "ঐ",
  I: "ও",
  J: "ঔ",
  K: "ক",
  L: "খ",
  M: "গ",
  N: "ঘ",
  O: "ঙ",
  P: "চ",
  Q: "ছ",
  R: "জ",
  S: "ঝ",
  T: "ঞ",
  U: "ট",
  V: "ঠ",
  W: "ড",
  X: "ঢ",
  Y: "ণ",
  Z: "ত",
  _: "থ",
  "`": "দ",
  a: "ধ",
  b: "ন",
  c: "প",
  d: "ফ",
  e: "ব",
  f: "ভ",
  g: "ম",
  h: "য",
  i: "র",
  j: "ল",
  k: "শ",
  l: "ষ",
  m: "স",
  n: "হ",
  o: "ড়",
  p: "ঢ়",
  q: "য়",
  r: "ৎ",
  s: "ং",
  t: "ঃ",
  u: "ঁ",
  "0": "০",
  "1": "১",
  "2": "২",
  "3": "৩",
  "4": "৪",
  "5": "৫",
  "6": "৬",
  "7": "৭",
  "8": "৮",
  "9": "৯",
  "•": "ঙ্",
  "|": "।",
};

export const PRE_SYMBOLS_MAP: Record<string, string> = {
  "®": "ষ্",
  "¯": "স্",
  "”": "চ্",
  "˜": "দ্",
  "™": "দ্",
  š: "ন্",
  "›": "ন্",
  "¤": "ম্",
};

export const REFF: Record<string, string> = {
  "©": "র্",
};

export const POST_SYMBOLS_MAP: Record<string, string> = {
  "&": "্‌",
  ú: "্প",
  è: "্ন",
  "^": "্ব",
  "‘": "্তু",
  "’": "্থ",
  "‹": "্ক",
  Œ: "্ক্র",
  "—": "্ত",
  Í: "্ত",
  œ: "্ন",
  Ÿ: "্ব",
  "¡": "্ব",
  "¢": "্ভ",
  "£": "্ভ্র",
  "¥": "্ম",
  "¦": "্ব",
  "§": "্ম",
  "¨": "্য",
  ª: "্র",
  "«": "্র",
  "¬": "্ল",
  "": "্ল",
  Ö: "্র",
};

export const KAARS: Record<string, string> = {
  v: "া",
  w: "ি",
  x: "ী",
  y: "ু",
  z: "ু",
  æ: "ু",
  "“": "ু",
  "–": "ু",
  "~": "ূ",
  ƒ: "ূ",
  "‚": "ূ",
  "„": "ৃ",
  "…": "ৃ",
  "†": "ে",
  "‡": "ে",
  ˆ: "ৈ",
  "‰": "ৈ",
  Š: "ৗ",
};

export const KAAR_POST_CONVERSION: Record<string, string> = {
  "ো": "ো",
  "ৌ": "ৌ",
};

export const POST_CONVERSION_MAP: Record<string, string> = {
  অা: "আ",
  "্‌্‌": "্‌",
};

export const ALL_SYMBOLS = {
  ...CONVERSION_MAP,
  ...PRE_SYMBOLS_MAP,
  ...POST_SYMBOLS_MAP,
};
