import { userRoleSchema } from "../types/roles";

export * from "./common";
export * from "./admin";
export * from "./banners";
export * from "./categories";
export * from "./comments";
export * from "./content";
export * from "./coupons";
export * from "./course-routines";
export * from "./courses";
export * from "./marking";
export * from "./math";
export * from "./messages";
export * from "./noticeboard";
export * from "./notifications";
export * from "./progress";
export * from "./reviews";
export * from "./seo";
export * from "./profiles";
export * from "./payments";
export * from "./sms";
export * from "./tests";
export * from "./uploads";
export { userRoleSchema };
