/**
 * The crawler-facing `/sitemap.xml` and `/robots.txt` are generated by the API,
 * but a crawler only ever asks the public origin for them. In development the
 * Vite proxy covers that; in production there is no guarantee of a proxy rule,
 * so the web app serves them itself and fetches the body from the API.
 *
 * This is the API's *root*, not its `/api/v1` prefix -- the SEO routes are
 * mounted above the version.
 */
export function apiRootUrl(): string {
  const raw = import.meta.env.VITE_SSR_API_BASE_URL;
  const base =
    typeof raw === "string" && raw.length > 0 ? raw : "http://127.0.0.1:3001/api/v1";

  return base.replace(/\/$/, "").replace(/\/api\/v1$/, "");
}

export async function fetchFromApiRoot(path: string): Promise<Response> {
  return fetch(`${apiRootUrl()}${path}`, { headers: { Accept: "*/*" } });
}
